### ISSUE TITLE
Is putting the password in the environment variable secure enough?

### ISSUE THREAD

**Issue by Laisky** [edgelesssys/edgelessdb#111]
I noticed that if you let the edgelessdb run in marblerun mode, marblerun injects the password(`masterKey`) into the container's environment variables

- https://docs.edgeless.systems/edgelessdb/#/advanced/marblerun
- https://github.com/Laisky/edgelessdb/blob/e712b823a0469e6f96cc57029477323ac0d47e2e/edb/core/key.go#L49

![23471659334560_ pic](https://user-images.githubusercontent.com/4532436/182085822-29a2c418-c15b-498a-a3f1-19d414a53a60.jpg)

we should assume that the platform is untrustworthy and protect our applications through Enclave. But the platform admin is able to view the environment variables of the container. So the admin can get the database encrypting paasword by looking at the environment variables?

**Comment by thomasten** [comment]
Similar to the SGX LibOSes, these environment variables only exist inside the enclave and aren't visible or accessible from the host.

**Comment by Laisky** [comment]
> Similar to the SGX LibOSes, these environment variables only exist inside the enclave and aren't visible or accessible from the host.

Thanks for the answer, I went to study the principle of marblerun, I misunderstood it before
