### ISSUE TITLE
fatal error: nanotime returning zero

### ISSUE THREAD

**Issue by henrysun007** [edgelesssys/edgelessdb#133]
When we run the DB on a vSGX environment,  `fatal error: nanotime returning zero` rised. The simulation mode DB has the same error. The OS version is `CentOS 8.5.2111`. However, when we run the DB in a bare-metal envrionment (CentOS 7.9.2009), the error was gone. The detailed error log is as below:

![image](https://user-images.githubusercontent.com/3353452/218026510-6a3d95a4-cf22-4241-a26d-71e5e22cc703.png)

**Comment by thomasten** [comment]
Do you use any of the published docker images? If so, please tell me its digest (get it with `docker images --digests`).

Or do you build it yourself?
If you use the Dockerfile for this, ensure that you use the latest.
If you build it manually, ensure that you use the latest version of EdgelessRT.

**Comment by henrysun007** [comment]
The digest is `sha256:668d43866609e7a93cec56cfa68c8ef5835e36244c8cecc57766b265e687f688`. It is an old release of edgelesssys/edgelessdb-sgx-1gb.

**Comment by thomasten** [comment]
The bug you encounter should be fixed in the latest version.

**Comment by henrysun007** [comment]
Thank you for your quick response. We switched to `ubuntu18.04` and the error was gone.
