### ISSUE TITLE
Where is edgelessdb looking for the my.cnf file?

### ISSUE THREAD

**Issue by beejones** [edgelesssys/edgelessdb#58]
Hi,

I am experimenting with your great project. I am trying to enable the audit_null mariadb plugin on my own build.
I've changed the CMakefile.txt:
 -DPLUGIN_AUDIT_NULL=YES

Where is edgelessdb looking for the my.cnf file?
I added my.cnf to /etc with the following content:

     [mysqld]
     plugin_dir=/home/ronny/edgelessdb/build/mariadb/plugin
     [mariadb]
     plugin_maturity=beta

PS: I also tried to put plugin_dir underneath the mariadb section.

These settings are not being picked up.
The plugin directory is still the default and I cannot load audit null which I moved to the default plugin location.

     INSTALL PLUGIN AUDIT_NULL SONAME 'adt_null.so';

ERROR 1126 (HY000): Can't open shared library 'adt_null.so' (errno: 1, Loading of unknown plugin AUDIT_NULL is prohibited by --plugin-maturity=gamma)

so  plugin_maturity is not being picked up eighter.

Thank in advance

**Comment by thomasten** [comment]
Hi,

Two things you need to know here:

The underlying SGX SDK doesn't support loading shared objects, so you need to statically link any required plugin. Please try if `-DPLUGIN_AUDIT_NULL=STATIC` works.

There is currently no way to use a custom my.cnf. Just loading it from the host would allow the host to attack the enclave. We should probably add support for user-supplied my.cnf's somehow. Maybe through the manifest.

**Comment by Laisky** [comment]
> Hi,
> 
> Two things you need to know here:
> 
> The underlying SGX SDK doesn't support loading shared objects, so you need to statically link any required plugin. Please try if `-DPLUGIN_AUDIT_NULL=STATIC` works.
> 
> There is currently no way to use a custom my.cnf. Just loading it from the host would allow the host to attack the enclave. We should probably add support for user-supplied my.cnf's somehow. Maybe through the manifest.

I think support for custom `my.cnf` is a very useful feature
