### ISSUE TITLE
edgelessdb & edgelessrt build and test problems

### ISSUE THREAD

**Issue by lijun0314** [edgelesssys/edgelessdb#69]
Hi, I got several problems when building edgelessrt & edgelessdb, here is details
About edgelessrt, the build step is no problem, but when I run ctest, the test result is:

98% tests passed, 6 tests failed out of 344

Total Test time (real) = 455.69 sec

The following tests did not run:
	 77 - tests/bigmalloc (Skipped)
	253 - tests/report_attestation_without_enclave (Skipped)

The following tests FAILED:
	 66 - tests/mbedtls_tls_e2e (Child aborted)
	 73 - tests/attestation_cert_api_mbedtls (Failed)
	 75 - tests/attestation_plugin_cert_mbedtls (Failed)
	252 - tests/report (Child aborted)
	309 - samples (Failed)
	318 - tests/ert/go_ra (Child aborted)
Errors while running CTest

I tried several to build it again but got the same ctest results. Can you figure out what's wrong?

About edgelessdb, the build step is wrong, the log is:
adminroot@adminroot:~/edgelessdb/build$ make -j`nproc`
[  5%] Built target genkey
[ 10%] Performing build step for 'mariadb'
[ 20%] Built target edb-lib
make[3]: warning: -jN forced in submake: disabling jobserver mode.
[  0%] Built target edgeless_o
[  0%] Built target vio
[  0%] Built target tpool
[  1%] Built target pcre2
[  1%] Built target wsrep_api_v26
[  4%] Built target readline
[  4%] Built target gen_lex_hash
[  4%] Built target mytap
[  4%] Built target gen_lex_token
[  4%] Built target mysql_clear_password
[  4%] Built target INFO_SRC
[  5%] Built target caching_sha2_password
[  5%] Built target cctap
[  5%] Built target sha256_password
[  5%] Built target dialog
[  5%] Built target mariadb_config
[  5%] Built target INFO_BIN
[  5%] Built target edgeless
[  8%] Built target client_ed25519
[ 11%] Built target ref10
[ 12%] Built target hsclient
[ 12%] Built target ma_getopt
[ 15%] Built target mariadb_obj
[ 15%] Built target comp_sql
[ 17%] Built target mysqlservices
[ 17%] Built target dbug-unit-tests
[ 17%] Built target my_safe_process
[ 18%] Built target wsrep-lib
[ 19%] Built target wsrep_check_version
[ 19%] Built target GenFixPrivs
[ 19%] Built target todo-t
[ 19%] Built target skip-t
[ 19%] Built target skip_all-t
[ 19%] Built target simple-t
[ 20%] Built target libmariadb
[ 20%] Built target no_plan-t
[ 20%] Built target mariadbclient
[ 28%] Built target mysys
[ 28%] Built target SYM_libmysqlclient.so
[ 28%] Built target SYM_libmysqlclient_r.so
[ 28%] Built target SYM_libmysqlclient.a
[ 28%] Built target dyncol
[ 28%] Built target SYM_libmysqlclient_r.a
[ 28%] Built target rpl_api
[ 28%] Built target ps_new
[ 28%] Built target fetch
[ 28%] Built target features-10_2
[ 29%] Built target thread
[ 29%] Built target basic-t
[ 29%] Built target misc
[ 30%] Built target t_aurora
[ 30%] Built target performance
[ 30%] Built target bulk1
[ 30%] Built target ps
[ 30%] Built target cursor
[ 31%] Built target connection
[ 31%] Built target conc336
[ 31%] Built target charset
[ 31%] Built target view
[ 31%] Built target async
[ 31%] Built target errors
[ 32%] Built target sp
[ 32%] Built target logs
[ 32%] Built target ps_bugs
[ 32%] Built target t_conc173
[ 32%] Built target result
[ 35%] Built target strings
[ 35%] Built target dbug
[ 35%] Built target abi_check
[ 35%] Built target bitmap-t
[ 35%] Built target strings-t
[ 35%] Built target my_malloc-t
[ 35%] Built target json-t
[ 35%] Built target lf-t
[ 36%] Built target base64-t
[ 36%] Built target my_rdtsc-t
[ 36%] Built target my_atomic-t
[ 36%] Built target my_getopt-t
[ 36%] Built target dynstring-t
[ 36%] Built target byte_order-t
[ 36%] Built target my_vsnprintf-t
[ 36%] Built target stacktrace-t
[ 36%] Built target crc32-t
[ 36%] Built target ma_dyncol-t
[ 37%] Built target comp_err
[ 37%] Built target mysys_ssl
[ 37%] Built target json_lib-t
[ 37%] Built target my_decimal-t
[ 37%] Built target queues-t
[ 37%] Built target tests
[ 37%] Built target my_apc-t
[ 37%] Built target factorial
[ 37%] Built target resolveip
[ 37%] Built target test_hash
[ 37%] Built target mariadbd-safe-helper
[ 37%] Built target replace
[ 37%] Built target thr_lock
[ 37%] Built target thr_timer
[ 38%] Built target my_print_defaults
[ 39%] Built target mariadb-conv
[ 39%] Built target mariadb-waitpid
[ 39%] Built target resolve_stack_dump
[ 39%] Built target user_ps
[ 39%] Built target GenError
[ 40%] Built target user_t
[ 40%] Built target aes-t
[ 40%] Built target ed25519-t
[ 40%] Built target udf_example
[ 40%] Built target mariadb-tzinfo-to-sql
[ 40%] Built target sql_sequence
[ 40%] Built target type_geom
[ 40%] Built target userstat
[ 40%] Built target mf_iocache-t
[ 41%] Built target type_inet
[ 41%] Built target csv
[ 41%] Built target mariadb-import
../../../src/google.golang.org/protobuf/encoding/prototext/decode.go:19:2: cannot find package "google.golang.org/protobuf/proto" in any of:
	/usr/src/google.golang.org/protobuf/proto (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/proto (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/proto
../../../src/github.com/golang/protobuf/proto/registry.go:16:2: cannot find package "google.golang.org/protobuf/reflect/protodesc" in any of:
	/usr/src/google.golang.org/protobuf/reflect/protodesc (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/reflect/protodesc (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/reflect/protodesc
../../../src/google.golang.org/protobuf/internal/encoding/messageset/messageset.go:13:2: cannot find package "google.golang.org/protobuf/reflect/protoreflect" in any of:
	/usr/src/google.golang.org/protobuf/reflect/protoreflect (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/reflect/protoreflect (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/reflect/protoreflect
../../../src/google.golang.org/protobuf/encoding/prototext/decode.go:21:2: cannot find package "google.golang.org/protobuf/reflect/protoregistry" in any of:
	/usr/src/google.golang.org/protobuf/reflect/protoregistry (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/reflect/protoregistry (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/reflect/protoregistry
../../../src/github.com/golang/protobuf/proto/extensions.go:16:2: cannot find package "google.golang.org/protobuf/runtime/protoiface" in any of:
	/usr/src/google.golang.org/protobuf/runtime/protoiface (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/runtime/protoiface (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/runtime/protoiface
../../../src/github.com/golang/protobuf/proto/buffer.go:13:2: cannot find package "google.golang.org/protobuf/runtime/protoimpl" in any of:
	/usr/src/google.golang.org/protobuf/runtime/protoimpl (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/runtime/protoimpl (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/runtime/protoimpl
../../../src/github.com/golang/protobuf/ptypes/any/any.pb.go:9:2: cannot find package "google.golang.org/protobuf/types/known/anypb" in any of:
	/usr/src/google.golang.org/protobuf/types/known/anypb (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/types/known/anypb (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/types/known/anypb
../../../src/github.com/golang/protobuf/ptypes/duration/duration.pb.go:9:2: cannot find package "google.golang.org/protobuf/types/known/durationpb" in any of:
	/usr/src/google.golang.org/protobuf/types/known/durationpb (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/types/known/durationpb (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/types/known/durationpb
../../../src/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go:9:2: cannot find package "google.golang.org/protobuf/types/known/timestamppb" in any of:
	/usr/src/google.golang.org/protobuf/types/known/timestamppb (from $GOROOT)
	/home/adminroot/go/src/google.golang.org/protobuf/types/known/timestamppb (from $GOPATH)
	/home/adminroot/src/google.golang.org/protobuf/types/known/timestamppb
../../../src/github.com/edgelesssys/ego/internal/attestation/maa.go:24:2: cannot find package "gopkg.in/square/go-jose.v2" in any of:
	/usr/src/gopkg.in/square/go-jose.v2 (from $GOROOT)
	/home/adminroot/go/src/gopkg.in/square/go-jose.v2 (from $GOPATH)
	/home/adminroot/src/gopkg.in/square/go-jose.v2
../../../src/github.com/edgelesssys/ego/internal/attestation/maa.go:25:2: cannot find package "gopkg.in/square/go-jose.v2/jwt" in any of:
	/usr/src/gopkg.in/square/go-jose.v2/jwt (from $GOROOT)
	/home/adminroot/go/src/gopkg.in/square/go-jose.v2/jwt (from $GOPATH)
	/home/adminroot/src/gopkg.in/square/go-jose.v2/jwt
../../../src/github.com/edgelesssys/marblerun/util/util.go:20:2: cannot find package "k8s.io/api/core/v1" in any of:
	/usr/src/k8s.io/api/core/v1 (from $GOROOT)
	/home/adminroot/go/src/k8s.io/api/core/v1 (from $GOPATH)
	/home/adminroot/src/k8s.io/api/core/v1
[ 43%] Built target heap
CMakeFiles/edb-noenclave-lib.dir/build.make:57: recipe for target 'CMakeFiles/edb-noenclave-lib' failed
make[2]: *** [CMakeFiles/edb-noenclave-lib] Error 1
CMakeFiles/Makefile2:390: recipe for target 'CMakeFiles/edb-noenclave-lib.dir/all' failed
make[1]: *** [CMakeFiles/edb-noenclave-lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Built target mariadb-check
[ 44%] Built target mariadb-slap
[ 44%] Built target mariadb-upgrade
[ 44%] Built target mariadb-dump
[ 44%] Built target mariadb-plugin
[ 44%] Built target mariadb-test
[ 44%] Built target mariadb-binlog
[ 46%] Built target myisammrg
[ 46%] Built target mariadb-admin
[ 46%] Built target async_example
[ 46%] Built target hp_test2
[ 47%] Built target mariadb
[ 47%] Built target mariadb-client-test
[ 47%] Built target mariadb-show
[ 47%] Built target bug25714
[ 47%] Built target perror
[ 51%] Built target myisam
[ 53%] Built target wsrep
[ 53%] Built target hp_test1
[ 53%] Built target myisam_ftdump
[ 53%] Built target mi_test1
[ 53%] Built target myisamchk
[ 53%] Built target myisamlog
[ 53%] Built target sp_test
[ 53%] Built target mi_test2
[ 53%] Built target rt_test
[ 53%] Built target myisampack
[ 54%] Built target mi_test3
[ 59%] Built target aria
[ 59%] Built target ma_test1
[ 59%] Built target aria_read_log
[ 60%] Built target aria_chk
[ 60%] Built target ma_test2
[ 60%] Built target ma_test3
[ 60%] Built target aria_pack
[ 60%] Built target ma_rt_test
[ 60%] Built target aria_dump_log
[ 60%] Built target aria_ftdump
[ 60%] Building CXX object storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/db/db_impl/db_impl.cc.o
[ 60%] Built target test_ma_backup
[ 60%] Built target ma_pagecache_rwconsist2_1k-t
[ 60%] Built target ma_pagecache_rwconsist_1k-t
[ 60%] Built target ma_sp_test
[ 61%] Built target ma_pagecache_consist_1kRD-t
[ 62%] Built target ma_control_file-t
[ 62%] Building CXX object storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file.cc.o
[ 62%] Built target ma_pagecache_consist_64k-t
[ 62%] Built target ma_pagecache_consist_1kHC-t
[ 62%] Building CXX object storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc.o
[ 63%] Built target ma_test_loghandler-t
[ 62%] Built target ma_pagecache_consist_64kRD-t
[ 63%] Built target ma_test_loghandler_pagecache-t
[ 63%] Built target ma_test_loghandler_first_lsn-t
[ 64%] Built target ma_test_loghandler_multigroup-t
[ 64%] Built target ma_pagecache_consist_1k-t
[ 64%] Built target ma_test_loghandler_multithread-t
[ 64%] Built target ma_pagecache_consist_1kWR-t
[ 64%] Built target ma_test_loghandler_long-t
[ 64%] Built target ma_test_loghandler_noflush-t
[ 64%] Built target ma_pagecache_consist_64kWR-t
[ 64%] Built target ma_test_loghandler_max_lsn-t
[ 64%] Built target ma_test_loghandler_purge-t
[ 65%] Built target ma_test_loghandler_nologs-t
[ 65%] Built target trnman-t
[ 65%] Built target ma_pagecache_consist_64kHC-t
[ 66%] Built target ma_pagecache_single_8k-t
[ 66%] Built target ma_pagecache_single_1k-t
[ 66%] Built target ma_test_loghandler_readonly-t
[ 66%] Built target ma_pagecache_single_64k-t
In file included from /home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file.cc:12:0:
/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/file_id.h:8:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
storage/rocksdb/CMakeFiles/rocksdblib.dir/build.make:2935: recipe for target 'storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file.cc.o' failed
make[5]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
In file included from /home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/db/db_impl/db_impl.cc:56:0:
/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/file_id.h:8:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
storage/rocksdb/CMakeFiles/rocksdblib.dir/build.make:283: recipe for target 'storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/db/db_impl/db_impl.cc.o' failed
make[5]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/db/db_impl/db_impl.cc.o] Error 1
[ 80%] Built target sql
/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc: In function ‘bool rocksdb::edg::WriteEncRecord(rocksdb::WritableFileWriter&, const rocksdb::Slice&, uint64_t)’:
/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc:41:70: sorry, unimplemented: non-trivial designated initializers not supported
   EncRecordHeader header{.size = static_cast<uint32_t>(record.size())};
                                                                      ^
/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc:41:70: warning: missing initializer for member ‘rocksdb::edg::EncRecordHeader::size’ [-Wmissing-field-initializers]
storage/rocksdb/CMakeFiles/rocksdblib.dir/build.make:2948: recipe for target 'storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc.o' failed
make[5]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/home/adminroot/edgelessdb/3rdparty/edgeless-rocksdb/file/encrypted_file_util.cc.o] Error 1
CMakeFiles/Makefile2:6102: recipe for target 'storage/rocksdb/CMakeFiles/rocksdblib.dir/all' failed
make[4]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/mariadb.dir/build.make:110: recipe for target 'mariadb-prefix/src/mariadb-stamp/mariadb-build' failed
make[2]: *** [mariadb-prefix/src/mariadb-stamp/mariadb-build] Error 2
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/mariadb.dir/all' failed
make[1]: *** [CMakeFiles/mariadb.dir/all] Error 2
[ 20%] Built target edb-golib
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

I am really confused about "cannot find package " problem, I downloaded the package by myself to solve it. But it seems to be a bad way, Is there any advice about this? 

Information about my machine:
Ubuntu 18.04, CPU supports SGX1 and FLC;
I follow the instructions to build edgelessrt and edgelessdb
https://github.com/edgelesssys/edgelessrt/tree/v0.2.7
https://github.com/edgelesssys/edgelessdb/blob/main/BUILD.md#build-from-source

Thanks

**Comment by lijun0314** [comment]
Hi @thomasten ,
I rebuild the project and then the OE_NOT_FOUND problem was solved. 
Thanks for your time and help!
Now, I started the PCCS service in my machine, the edgelessdb started OK, and successfully got the quote. But when I run `era` command, errors happened, here is the output:
```
adminroot@adminroot:~/edgelessdb$ era -c edgelessdb-sgx.json -h localhost:8080 -output-root edb.pem
2021-11-03T06:17:19+0000.660544Z [(H)ERROR] tid(0x7f7ed6abeb80) | Invalid platform TCB level: ConfigurationAndSWHardeningNeeded (cpu_svn[0] = 0x11, pce_svn = 0xb) [/edgelessrt/build/3rdparty/openenclave/openenclave-src/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:825]
2021-11-03T06:17:19+0000.661205Z [(H)ERROR] tid(0x7f7ed6abeb80) | :OE_TCB_LEVEL_INVALID [/edgelessrt/build/3rdparty/openenclave/openenclave-src/common/sgx/quote.c:oe_verify_sgx_quote:491]
2021-11-03T06:17:19+0000.661212Z [(H)ERROR] tid(0x7f7ed6abeb80) | :OE_TCB_LEVEL_INVALID [/edgelessrt/build/3rdparty/openenclave/openenclave-src/host/sgx/hostverify_report.c:oe_verify_remote_report:46]
panic: OE_TCB_LEVEL_INVALID

goroutine 1 [running]:
main.main()
	/__w/era/era/cmd/era/main.go:47 +0xc5f
```
About PCCS, I had tested it by running `SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample`, the sample output is:
```
adminroot@adminroot:~/test-dcap/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample$ ./app 
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:succeed!
Step2: Call create_app_report:succeed!
Step3: Call sgx_qe_get_quote_size:succeed!
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
sgx_qe_cleanup_by_policy is valid in in-proc mode only.

 Clean up the enclave load policy:succeed!
```
I had a checkout that openenclave SDK allow TCB level information, the document is `https://github.com/openenclave/openenclave/blob/v0.17.1/docs/DesignDocs/SGX_QuoteVerify_Integration.md`
And I also find some solutions in `https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/152`, I was tried to solve it, but  I am still not sure why `invalid platform TCB level` occurs. From your document `https://github.com/edgelesssys/era`, there is little information about PCCS, if there is some additional configure about the `era` when I used my own PCCS service?

**Comment by thomasten** [comment]
The error is ConfigurationAndSWHardeningNeeded, which can be divided into
* ConfigurationNeeded: this usually means that you need to disable Hyperthreading
* SWHardeningNeeded: this often means that you need to update the BIOS/UEFI

Both needs to be done for the machine that runs the enclave, not the machine that runs era.

You can run era with `OE_LOG_LEVEL=INFO era ...` and maybe then you'll get more concrete info what's wrong.

**Comment by jiangbinghua** [comment]
I disable Hyperthreading，but the error is ConfigurationAndSWHardeningNeeded too.

**Comment by thomasten** [comment]
We will release a new version of era soon that will optionally allow to ignore the error.
According to https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/152#issuecomment-754020011 you may also need to disable the iGPU if your system has one.

To summarize, on the machine that runs the enclave
* update to the latest BIOS
* disable Hyperthrading
* disable iGPU

**Comment by thomasten** [comment]
We just released the new version of era. You are now able to accept this TCB status.

**Comment by lijun0314** [comment]
Hi @thomasten ,
Sorry to reply so late, work on EdgelessDB is still in progress.

**Comment by lijun0314** [comment]
Hi, @thomasten 
Sorry to reply so late, work on EdgelessDB is still in progress.
We have tested the new version of era, it works well!
I will close this issue, thank you very much for your time and help, again!
