### ISSUE TITLE
The database server container failed to restart

### ISSUE THREAD

**Issue by henrysun007** [edgelesssys/edgelessdb#74]
I ran `ghcr.io/edgelesssys/edgelessdb-sgx-1gb:lastest` with image `ID: ba1fa216a071` on my `CentOS Linux release 7.9.2009 (Core)`. It failed to restart the container afterwards. I found https://github.com/edgelesssys/edgelessdb/blob/8c1df2066513153ac9b8e129a0924abe431e3191/src/entry.sh#L10 blocked the start. It raised an error `File exists` if `/usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so` had already existed.

**Comment by thomasten** [comment]
Thanks for reporting! We'll fix it.

**Comment by thomasten** [comment]
I pushed a new `ghcr.io/edgelesssys/edgelessdb-sgx-1gb`. Can you pull and try?

**Comment by henrysun007** [comment]
Yes, the container can be restarted successfully.
