### ISSUE TITLE
Lost connection to MySQL?

### ISSUE THREAD

**Issue by X1anWang** [edgelesssys/edgelessdb#77]
**My platform and version choosing.** My cloud is run on Linux ubuntu 16.04 with Intel SGX. But the recommended DCAP SGX Driver version requests library of <linux/sched/mm.h> for its installing which seems not supported for my linux kernel version 4.04. So I did not install SGX driver and choose the SIMULATION MODE.

**My approach.** I did as the instruction ([https://docs.edgeless.systems/edgelessdb/#/getting-started/quickstart-simulation](url)) for simulation mode, did not install any other tools (e.g. era), and skipped its verification operation.
NOTE: Because it prompted there was a confliction with port 3306 when I initialized the docker container and I found my MySQL was in use and occupied the port 3306, I stopped the service of MySQL, and the docker container was initialized successfully then.

**My problem.** When I execute the last shell
`mysql -h127.0.0.1 -uroot --ssl-ca edb.pem --ssl-cert cert.pem --ssl-key key.pem`
It prompts
`ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`
And now, the created docker container is still running and can be entered. MySQL cannot be entered by commend "mysql" because of bad connection through socket. And MySQL cannot be started by commend "service mysql start" because of timing out.

**Comment by thomasten** [comment]
Hi @X1anWang,
If you skip verification with era, you must omit the `--ssl-ca` argument of the mysql command:
```
mysql -h127.0.0.1 -uroot --ssl-cert cert.pem --ssl-key key.pem
```
I see that this info is missing in the docs, will add it.

You can kill and delete the container with
```
docker rm -f my-edb
```

If you want to run both MySQL and EdgelessDB at the same time, you can recreate it with another SQL port, e.g. 3307, and connect to it:
```
docker run --name my-edb -p3307:3306 -p8080:8080 -e OE_SIMULATION=1 -t ghcr.io/edgelesssys/edgelessdb-sgx-1gb
...
mysql -h127.0.0.1 -P3307 -uroot --ssl-cert cert.pem --ssl-key key.pem
```
