### ISSUE TITLE
The result of test of EDB is FAILED

### ISSUE THREAD

**Issue by swpuliuchuan** [edgelesssys/edgelessdb#83]
Hi @thomasten ,
Now, the edgelessdb has installed and worked successfully in my server. But when I execute` ctest --output-on-failure` in `edgelessdb/build`.The output is:
`Test project /root/edgelessdb/build
    Start 1: unit-tests
1/3 Test #1: unit-tests .......................***Failed    1.35 sec
cmd/edb/error.go:25:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/core" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOPATH)
cmd/edb/error.go:26:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/db" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/db (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/db (from $GOPATH)
cmd/edb/invokemain.go:20:8: cannot find package "github.com/edgelesssys/edgelessdb/edb/rt" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/rt (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/rt (from $GOPATH)
cmd/edb/run.go:21:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/server" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/server (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/server (from $GOPATH)
cmd/edb/main.go:30:2: cannot find package "github.com/edgelesssys/marblerun/marble/premain" in any of:
        /snap/go/9028/src/github.com/edgelesssys/marblerun/marble/premain (from $GOROOT)
        /root/go/src/github.com/edgelesssys/marblerun/marble/premain (from $GOPATH)
cmd/edb/error.go:27:2: cannot find package "github.com/fatih/color" in any of:
        /snap/go/9028/src/github.com/fatih/color (from $GOROOT)
        /root/go/src/github.com/fatih/color (from $GOPATH)
cmd/edb/run.go:23:2: cannot find package "github.com/spf13/afero" in any of:
        /snap/go/9028/src/github.com/spf13/afero (from $GOROOT)
        /root/go/src/github.com/spf13/afero (from $GOPATH)
edb/core/core.go:41:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/util" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/util (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/util (from $GOPATH)
edb/core/key.go:27:2: cannot find package "github.com/edgelesssys/ego/ecrypto" in any of:
        /snap/go/9028/src/github.com/edgelesssys/ego/ecrypto (from $GOROOT)
        /root/go/src/github.com/edgelesssys/ego/ecrypto (from $GOPATH)
edb/core/core.go:42:2: cannot find package "github.com/edgelesssys/ego/marble" in any of:
        /snap/go/9028/src/github.com/edgelesssys/ego/marble (from $GOROOT)
        /root/go/src/github.com/edgelesssys/ego/marble (from $GOPATH)
edb/db/mariadb.go:37:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
        /snap/go/9028/src/github.com/go-sql-driver/mysql (from $GOROOT)
        /root/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
Start 2: integration-noenclave
2/3 Test #2: integration-noenclave ............***Failed    0.25 sec
_/root/edgelessdb/edb
edb/integration_test.go:51:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/core" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOPATH)
FAIL    _/root/edgelessdb/edb [setup failed]
FAIL
    Start 3: integration
3/3 Test #3: integration ......................***Failed    0.25 sec
_/root/edgelessdb/edb
edb/integration_test.go:51:2: cannot find package "github.com/edgelesssys/edgelessdb/edb/core" in any of:
        /snap/go/9028/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOROOT)
        /root/go/src/github.com/edgelesssys/edgelessdb/edb/core (from $GOPATH)
FAIL    _/root/edgelessdb/edb [setup failed]
FAIL

0% tests passed, 3 tests failed out of 3

Total Test time (real) =   1.85 sec

The following tests FAILED:
          1 - unit-tests (Failed)
          2 - integration-noenclave (Failed)
          3 - integration (Failed)
Errors while running CTest`
 Did I need to fix this errors by download files, or this errors can be ignored by editing the test file？

**Comment by thomasten** [comment]
This might be an issue related to Go modules. Can you post the output of `go env` while being in the `edgelessdb/build` directory?

**Comment by swpuliuchuan** [comment]
the output is:
`GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/9028"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/9028/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build509864792=/tmp/go-build -gno-record-gcc-switches"`
And I didnt find the packages in {GOROOT} & {GOPATH}.

**Comment by thomasten** [comment]
GO111MODULE must not be off. Have you set GO111MODULE variable in your environment? If you don't want to change that, you can run the test with temporarily cleared variable with `GO111MODULE= ctest --output-on-failure`

**Comment by swpuliuchuan** [comment]
Hi, @thomasten 
 Thank you for replaying. Now, I set the `GO111MODULE=ON` and execute `ctest --output-on-failure` .The output is:
`    Start 1: unit-tests
1/3 Test #1: unit-tests .......................   Passed   24.19 sec
    Start 2: integration-noenclave
2/3 Test #2: integration-noenclave ............***Failed    5.74 sec
# github.com/edgelesssys/ertgolib/erthost
../go/pkg/mod/github.com/edgelesssys/ertgolib@v0.1.5-0.20210208080427-0d5e24e2f855/erthost/erthost.go:6:11: fatal error: openenclave/host_verify.h: No such file or directory
    6 | // #include <openenclave/host_verify.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAIL    github.com/edgelesssys/edgelessdb/edb [build failed]
FAIL

    Start 3: integration
3/3 Test #3: integration ......................***Failed    0.71 sec
# github.com/edgelesssys/ertgolib/erthost
../go/pkg/mod/github.com/edgelesssys/ertgolib@v0.1.5-0.20210208080427-0d5e24e2f855/erthost/erthost.go:6:11: fatal error: openenclave/host_verify.h: No such file or directory
    6 | // #include <openenclave/host_verify.h>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAIL    github.com/edgelesssys/edgelessdb/edb [build failed]
FAIL
`
But, I find existence of the file
 root@adminroot:~/edgelessrt# find . -name host_verify.h
./build/3rdparty/openenclave/openenclave-src/include/openenclave/host_verify.h
./build/3rdparty/openenclave/openenclave-src/tools/oeedger8r-cpp/test/virtual/include/openenclave/host_verify.h
./build/3rdparty/openenclave/openenclave-install/include/openenclave/host_verify.h
./build/3rdparty/openenclave/openenclave/install/root/edgelessrt/build/3rdparty/openenclave/openenclave-install/include/openenclave/host_verify.h
./build/3rdparty/openenclave/openenclave/tools/oeedger8r-cpp-src/test/virtual/include/openenclave/host_verify.h
./3rdparty/openenclave/openenclave/include/openenclave/host_verify.h
./3rdparty/openenclave/openenclave/tools/oeedger8r-cpp/test/virtual/include/openenclave/host_verify.h`
`
I guess there are some steps that I missed. So, I add the ert to the env `. /opt/edgelessrt/share/openenclave/openenclaverc`
Now the output is:
`Test project /root/edgelessdb/build
    Start 1: unit-tests
1/3 Test #1: unit-tests .......................   Passed   13.33 sec
    Start 2: integration-noenclave
2/3 Test #2: integration-noenclave ............   Passed   23.44 sec
    Start 3: integration
3/3 Test #3: integration ......................   Passed  149.15 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) = 185.93 sec`
So, the success of tests which have to add ert to env? And, I set the GO111MODULE = ON, what if it will make effects to EDB?

**Comment by thomasten** [comment]
> So, I add the ert to the env `. /opt/edgelessrt/share/openenclave/openenclaverc`

Yes, this is the correct step. The test needs to link against ERT.

> I set the GO111MODULE = ON, what if it will make effects to EDB?

As most modern Go projects, EDB uses Go modules to manage dependencies. So this is just a requirement to build both EDB as well as its tests.

**Comment by swpuliuchuan** [comment]
Hi, @thomasten .
  Thank you for replying. The question is solved.Now, I want to test the performance with sysbench. When I create the database, the edb has aborted. The output is:
 `host is: 0.0.0.0[EDB] 2022/03/13 10:16:59 starting up ...
2022-03-13 10:16:59 0 [Note] edb (mysqld 10.5.11-MariaDB-debug-log) starting as process 1242246 ...
2022-03-13 10:16:59 0 [Warning] You need to use --log-bin to make --binlog-format work.
2022-03-13 10:17:00 0 [Note] Initializing built-in plugins
2022-03-13 10:17:00 0 [Note] Initializing plugins specified on the command line
2022-03-13 10:17:00 0 [Note] RocksDB: 4 column families found
2022-03-13 10:17:00 0 [Note] RocksDB: Column Families at start:
2022-03-13 10:17:00 0 [Note]   cf=default
2022-03-13 10:17:00 0 [Note]     write_buffer_size=67108864
2022-03-13 10:17:00 0 [Note]     target_file_size_base=67108864
2022-03-13 10:17:00 0 [Note]   cf=__system__
2022-03-13 10:17:00 0 [Note]     write_buffer_size=67108864
2022-03-13 10:17:00 0 [Note]     target_file_size_base=67108864
2022-03-13 10:17:00 0 [Note]   cf=edg_db_cf
2022-03-13 10:17:00 0 [Note]     write_buffer_size=67108864
2022-03-13 10:17:00 0 [Note]     target_file_size_base=67108864
2022-03-13 10:17:00 0 [Note]   cf=edg_frm_cf
2022-03-13 10:17:00 0 [Note]     write_buffer_size=67108864
2022-03-13 10:17:00 0 [Note]     target_file_size_base=67108864
2022-03-13 10:17:00 0 [Note] RocksDB: Removing incomplete create index (0,300)
2022-03-13 10:17:00 0 [Warning] RocksDB: Schema mismatch - A .frm file exists for table mysql.#sql-alter-12e492-8, but that table is not registered in RocksDB
2022-03-13 10:17:00 0 [ERROR] RocksDB: Problems validating data dictionary against .frm files, exiting
2022-03-13 10:17:00 0 [ERROR] RocksDB: Failed to initialize DDL manager.
2022-03-13 10:17:00 0 [ERROR] Plugin 'ROCKSDB' init function returned error.
2022-03-13 10:17:00 0 [ERROR] Plugin 'ROCKSDB' registration as a STORAGE ENGINE failed.
2022-03-13 10:17:00 0 [Note] Initializing installed plugins
2022-03-13 10:17:00 0 [ERROR] Could not open mysql.plugin table: "Unknown storage engine 'ROCKSDB'". Some plugins may be not loaded
2022-03-13 10:17:00 0 [ERROR] Failed to initialize plugins.
2022-03-13 10:17:00 0 [ERROR] Aborting
Warning: Memory not freed: 8784
edb has exited unexpectedly (exit code: 1).`
And when I start it again, it will exit unexpectedly too.

**Comment by thomasten** [comment]
Can you provide the steps to reproduce this from scratch?

**Comment by thomasten** [comment]
Closing this. Feel free to reopen if there are still issues.
