### ISSUE TITLE
edb reports "ERROR: not implemented" during boot and crashes when receives "CTRL + C"

### ISSUE THREAD

**Issue by Glenrun** [edgelesssys/edgelessdb#85]
after i built EdgelessDB successfully on my `ubuntu 20.04`, `kernel 5.4.0-89-generic`, ert installed `edgelessrt_0.3.0_amd64.deb`
I booted edb from command line:
`edgelessdb/build# ./edb`
It reports error:
```
[erthost] loading enclave ...
[erthost] entering enclave ...
[EDB] 2022/03/04 15:56:09 EdgelessDB v0.2.1 (22c6a1b78674802ce315bc3620b3a869c306894e)
[EDB] 2022/03/04 15:56:09 starting up ...
2022-03-04 15:56:09 0 [Note] edb (mysqld 10.5.11-MariaDB-debug) starting as process 2967722 ...
ERROR: sched_getaffinity: pid: Function not implemented [src/ertlibc/syscall.cpp:ert_syscall:158]
ERROR: not implemented: fedisableexcept [src/ertlibc/stubs.cpp:ert_stub_trace:9]
```

if I run mariaDB tests follow [BUILD.md](https://github.com/edgelesssys/edgelessdb/blob/main/BUILD.md)
another error shown:
`ERROR: not implemented: mallinfo [src/ertlibc/stubs.cpp:ert_stub_trace:9]`

after I enter `CTRL+C`, it crashed:
```
./edb: line 3: 2967722 Segmentation fault      (core dumped) erthost "$DIR/edb-enclave.signed" "$@"
```

**Comment by thomasten** [comment]
The `not implemented` errors can be seen on debug enclaves builds, but you can ignore them. I placed a hint about this in
 https://github.com/edgelesssys/edgelessdb/blob/main/BUILD.md#not-implemented-errors

We haven't implemented clean shutdown yet, but this shouldn't impair functionality and can be ignored.
