### ISSUE TITLE
Support and security issues

### ISSUE THREAD

**Issue by lijun0314** [edgelesssys/edgelessdb#87]
Hi, @thomasten,
I have two questions。
Does EdgelessDB support running java programs inside the enclave?
And I want to know is it safe for me to manipulate the database in this way?
One machine, start the edgelessdb database and operate the database inside enclave.
Set `test` in manifest.json,
```json
{
    "sql": [
        "CREATE USER root REQUIRE ISSUER '/CN=My CA' SUBJECT '/CN=rootuser'",
        "GRANT ALL ON *.* TO root WITH GRANT OPTION",
	"CREATE USER test IDENTIFIED BY '123'",
        "grant all privileges on *.* to test@'%' with grant option",
        "flush privileges"
    ],
    "ca": "-----BEGIN CERTIFICATE-----\nMIIDATCCAemgAwIBAgIUfVlQIGpmfApr5zMnhCTOksTMyUQwDQYJKoZIhvcNAQEL\nBQAwEDEOMAwGA1UEAwwFTXkgQ0EwHhcNMjExMjMwMDMwODMxWhcNMzExMjI4MDMw\nODMxWjAQMQ4wDAYDVQQDDAVNeSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC\nAQoCggEBAM33GlaTcBlqyBzomTZ84KDdbMzZv7WTi0ttl3mSRVawZjwP0bXRyTPT\nBbXqCYxoCNSeBciuivi9Wo8IxenOaXkN1wSzCjmGhWo0cU1QvEcX44UBL70uk3Gg\nVGL/E0Vi9NaIQDj9PXng8w23QfOLgWw6R0fRPgichVFKA4iU7OypQMqNirO8iIlY\nLz9Z8Z28z6QkOhpS7jKZuOnGnRX6/gkwCghUzZ6yHa3a1oWkA0ANiyMy+J3pAS/N\ncShPiwygZWMNImYYttpKfl/x4iM8yt3SoN6wNNmW4c3NfHrHz1tMJrtYcG7apzXn\nax8dbzZAifNsUhKhFoEUfFmq0ERH3IcCAwEAAaNTMFEwHQYDVR0OBBYEFGjLZBN8\nLdbeiqrkahcG+ZEe805fMB8GA1UdIwQYMBaAFGjLZBN8LdbeiqrkahcG+ZEe805f\nMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAMNhuGrO/YpjE5pd\nNm/S4QUzHqsOPEPS86QB5u3vSxa548V8U8cB/2f18jWYSYZ1HpFoBmifXrKCaAEx\n6pNwfOVEMJAeuAgnOaclA7x0tn9wJtwJ8fHRzCxmc2o4RQXriXl5M7LU2RxJ1+3O\nygeczwTQpQ2PyIJWy7LbdsXr9QxFUNFRX9JBJCg+Tezo9UCkQ2k05GMgZru0gr2h\nVnIp25WXEHoSqlkgCc/65b0JrX//GIXgVEUxMOld2bMu9POHAitL4e0z/5JC2U7C\nS438HALNWWkzsyyZ7E7r2mt46ziTEqLY06QizpdyDugTkP6WmvVlnQxXISDjTnMS\nVER9mFE=\n-----END CERTIFICATE-----\n",
	"debug": true
}
```
I open the database inside enclave to access `test`, but I have to add the `?tls=skip-verify` to open it properly, otherwise it will report an error.
```mysql
func sqlOpen(address string) (*sql.DB, error) {
	return sql.Open("mysql", "test:123@tcp("+address+")/?tls=skip-verify")
}
```
Without `?tls=skip-verify`, the error is
```
2022-03-18  9:10:09 5 [Warning] Access denied for user 'test'@'127.0.0.1' (using password: YES)
2022-03-18  9:10:09 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'test' host: '127.0.0.1' (This connection closed normally)
```
So, I'm not sure if it's safe to access the database in this way using `?tls=skip-verify`. If this approach is not safe, what can I do to fix it?
Looking forward to your reply, thanks!

**Comment by thomasten** [comment]
EdgelessDB doesn't support Java inside the same enclave. But you may be able to run Java in another TEE runtime like [Gramine](https://github.com/gramineproject/gramine), [Occlum](https://github.com/occlum/occlum), or [Mystikos](https://github.com/deislabs/mystikos) and then establish a secure TLS connection to EdgelessDB.

Regarding the second question, I understand that this code is running inside the EdgelessDB enclave. Connecting with `skip-verify` isn't secure because the connection will exit the enclave and re-enter it. Once EdgelessDB has started up, there's currently no way to make an enclave-internal connection to the SQL DB. Thus, you need to do something like
https://github.com/edgelesssys/edgelessdb/blob/5fa732b73834fdfb015f1094f81fed1e877ca23e/edb/integration_test.go#L910-L919
(If using password auth, you don't need `cert`, but only `serverCert`.)

You can get the required server root certificate from
https://github.com/edgelesssys/edgelessdb/blob/5fa732b73834fdfb015f1094f81fed1e877ca23e/edb/db/mariadb.go#L118

**Comment by lijun0314** [comment]
Thanks for your reply!
I tried to use `sql.Open("mysql", user+"@tcp("+addrDB+")/?tls=custom"` ，but ran into problems.
Here is the detail,
```golang
func createClient(address string) (err error) {
	cert := db.GetCertificateSql()  //get cert from func (d *Mariadb) GetCertificate() ([]byte, crypto.PrivateKey)
	fmt.Println("cert is: ", cert)  //check out the cert content is right or not
	pemCert := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert})
	if len(pemCert) <= 0 {
		fmt.Println("failed to encode certificate")
	}
	dbtee, err = sqlOpenTEE(address, string(pemCert))
	if err != nil {
		fmt.Printf("sqlOpen failed ...\n")
		return
	}
	defer dbtee.Close()
	fmt.Printf("check clientTable ...\n")
        createTable := `CREATE TABLE IF NOT EXISTS client (client_id CHAR(34) NOT NULL, client_iv CHAR(17) NOT NULL, client_key  CHAR(17) NOT NULL, login_name CHAR(41) NOT NULL, PRIMARY KEY (client_id) USING BTREE)`
	_, errExec := dbtee.Exec(createTable)
      if errExec != nil {
		fmt.Printf("CREATE TABLE IF NOT EXISTS client failed!\n")
		panic(errExec)
      }

	return
}

func sqlOpenTEE(address, serverCert string) (*sql.DB, error) {

	tlsCfg := tls.Config{
		RootCAs:      x509.NewCertPool(),
	}
	if ok := tlsCfg.RootCAs.AppendCertsFromPEM([]byte(serverCert)); !ok {
		panic("AppendCertsFromPEM failed")
	}
	mysql.RegisterTLSConfig("custom", &tlsCfg)
	db, err := sql.Open("mysql", "test:123@tcp("+address+")/mysql?tls=custom")
	if err != nil {
		panic(err)
	} else {
		fmt.Println("sql.Open success.")
	}
	return db, err
}
```
When working with the database, I encountered the following error
```
...
sql.Open success.
checkclientTable ...
CREATE TABLE IF NOT EXISTS client failed!
2022-03-24  8:09:29 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '127.0.0.1' (This connection closed normally without authentication)
panic: x509: cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs
```
Then, I try to regain the cert, in the form of the following code, it turns out the same error.
https://github.com/edgelesssys/edgelessdb/blob/5d8788a744675fcde24ba02219b643915efef641/edb/core/core.go#L267
What should I do to solve the problem of certificate verification failure?

**Comment by thomasten** [comment]
try "localhost" instead of 127.0.0.1 as address

**Comment by lijun0314** [comment]
"localhost" worked, thanks!
