### ISSUE TITLE
Does EdgelessDB support backup?

### ISSUE THREAD

**Issue by lijun0314** [edgelesssys/edgelessdb#92]
Hi, @thomasten,
Does EdgelessDB support the backup feature? I understand that MariaDB supports [backups](https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/).
When I searched for `mariabackup`, I saw a lot of source code for backups in `edgeless-mariadb`. But I'm not sure if it works and how to use it. Can you tell me more about it?
And does EdgelessDB support [Setting Up Replication](https://mariadb.com/kb/en/setting-up-replication/)?

**Comment by thomasten** [comment]
Hi,
We haven't tried mariabackup yet. I just gave it a quick try and it failed to connect. Even if it would, I think it might fail because of the modified encryption at RocksDB level.
So currently you have to stop EdgelessDB and copy the data folder to create a backup. Or use something like `mysqldump`.

There's currently no support for replication.

**Comment by lijun0314** [comment]
Thanks for your reply! 
Is it safe to say that EdgelessDB is not suitable for distributed shared data scenarios? Suppose I deploy multiple EdgelessDB databases, which can only run services individually because the data in each database cannot be synchronized in real-time. If a database crashes, it cannot switch to another database to continue to provide services.

**Comment by thomasten** [comment]
Yes, this is true for the current version. It's on our long-term roadmap though.

**Comment by lijun0314** [comment]
Hi, @thomasten,
If use [marblerun](https://github.com/edgelesssys/marblerun), deploy multiple edgelessdb services in a distributed environment, i.e. edgelessdb A, B, C. 
For databases A, B, and C:
First, can A, B, and C interact securely and in real-time?
Second, can A, B, and C data be synchronized in real-time? If not, is it possible to implement database backup in marblerun?

**Comment by thomasten** [comment]
No, unfortunately, none of this is supported yet.

**Comment by lijun0314** [comment]
Understood, thanks for your reply!

**Comment by gammelgaard52** [comment]
Is it supported today?

**Comment by thomasten** [comment]
No, all statements are still true.
